name: final_year_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_3d_controller: ^2.0.2
  syncfusion_flutter_calendar: ^28.2.6
  firebase_core: ^3.12.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.5.0
  intl: ^0.20.2
  lottie: ^3.3.1
  provider: ^6.1.2
  audioplayers: ^6.1.1
  #flutter_treeview: ^1.0.6
  #flutter_simple_treeview: ^3.0.2
  #tree_view: ^0.1.5
  #animated_tree_view: ^2.3.0
  graphite: ^1.2.0
  
  google_sign_in: ^6.2.2
  flutter_secure_storage: ^9.2.4
  googleapis: ^13.2.0
  http: ^1.3.0
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  firebase_messaging: ^15.2.3
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  share_plus: ^10.1.4
  csv: ^6.0.0
  url_launcher: ^6.3.1
  speech_bubble: ^0.0.9
  bubble: ^1.2.1
  flutter_widgetkit: ^1.0.3
  home_widget: ^0.7.0+1
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.2
  flutter_svg: ^2.0.17
  speech_to_text: ^7.0.0
  firebase_auth_mocks: ^0.14.1
  flutter_neumorphic: ^3.2.0
  screenshot: ^3.0.0




dev_dependencies:
  integration_test: 
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
  fake_cloud_firestore: ^3.1.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  firebase_core_platform_interface: ^5.4.0
  audioplayers: ^6.1.1
  firebase_analytics_platform_interface: ^4.3.4
  firebase_core: ^3.12.0
  path_provider_platform_interface: ^2.1.2
  audioplayers_platform_interface: ^7.0.1
  mocktail: ^1.0.4
  glob: ^2.1.2



flutter:
  uses-material-design: true
  assets:

    - assets/bird.obj 
    - assets/bird.mtl
    - assets/test.glb
    - assets/animated/
    - assets/audio/
    - assets/adhdAlien.jpg
    - assets/logoYoutube.png
    - assets/others/bubbleChat.svg
    - assets/
